# Generated by Django 3.0.3 on 2020-03-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.CharField(blank=True, max_length=1000, null=True)),
                ('slinks', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
