# Generated by Django 3.0.3 on 2020-03-29 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('long_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('short_hash', models.CharField(blank=True, max_length=1000, null=True)),
                ('no_clicks', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='working',
        ),
    ]
