# Generated by Django 3.0.3 on 2020-03-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_auto_20200329_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltable',
            name='no_clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
