# Generated by Django 3.0.3 on 2020-03-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0006_auto_20200330_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltable',
            name='no_clicks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
