# Generated by Django 3.0.3 on 2020-03-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0008_auto_20200330_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltable',
            name='no_clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
